//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportStore.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
        
        public string ProductPriceWithoutDiscount
        {
            get
            {
                if(ProductDiscount > 0)
                {
                    return ProductPrice.ToString() + " руб.";
                }
                else
                {
                    return string.Empty;
                }
            }
        }

        public string ProductPriceWithDiscount
        {
            get
            {
                if (ProductDiscount > 0)
                {
                    return ((double)ProductPrice * (1 - (double)ProductDiscount /100)).ToString() + " руб.";
                }
                else
                {
                    return ProductPrice.ToString();
                }
            }
        }

        public string ProductManufactureName
        {
            get
            {
                return App.Context.Manufactures.FirstOrDefault(x => x.ManufactureID == ProductManufacture).ManufactureName.ToString();
            }
        }

        public string ProductQuantityInOrder { get; set; }


        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public decimal ProductPrice { get; set; }
        public int ProductDiscount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public int ProductManufacture { get; set; }
        public string ProductImage { get; set; }
    
        public virtual Manufacture Manufacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
